sudo: false
language: node_js
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: JOB_PART=lint
    - os: linux
      node_js: "7"
      env: JOB_PART=benchmark
    - os: linux
      node_js: "6"
      env: JOB_PART=test
    - os: linux
      node_js: "7"
      env: JOB_PART=test
before_install:
  - nvm --version
  - node --version
  - npm install -g bithound
script:
  - npm run travis:$JOB_PART
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git
after_success:
  - bash <(curl -s https://codecov.io/bash)
